version: '3'
services:
  backend:
    container_name: backend-server
    image: yourdockerhubusername/app-with-actions:latest
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: your-rds-endpoint.ap-northeast-2.rds.amazonaws.com
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app12345
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
